name: Docker Image CI

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main", "develop", "feature/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      IMAGE_TAG: v0.0.1
      IMAGE_NAME: node-redis
      CONTAINER_NAME: redis-container
      CONTAINER_PORT: 6379
      REDIS_VOLUME_NAME: redis-data

    steps:
    - uses: actions/checkout@v4

    - name: Set IMAGE_URI
      id: set-image-uri
      run: echo "IMAGE_URI=${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --tag ${{ env.IMAGE_URI }} || { echo 'Build failed!'; exit 1; }

    - name: Run the Docker container
      run: |
        docker run -d \
          --name ${{ env.CONTAINER_NAME }} \
          -v ${{ env.REDIS_VOLUME_NAME }}:/data \
          ${{ env.IMAGE_URI }} || { echo 'Run failed!'; exit 1; }

    - name: Health Check
      run: |
        for i in {1..20}; do
          sleep 3
          if docker exec ${{ env.CONTAINER_NAME }} redis-cli -h localhost -p ${{ env.CONTAINER_PORT }} PING 2>/dev/null; then
            exit 0
          fi
          echo "Waiting for ${{ env.CONTAINER_NAME }} to start..."
        done
        echo "Health check failed!"
        exit 1

    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_URI }}

    - name: Cleanup
      if: always()
      run: |
        docker stop ${{ env.CONTAINER_NAME }} || echo "Container not running or already stopped."
        docker rm ${{ env.CONTAINER_NAME }} || echo "Container not found."
        dangling_images=$(docker images -f "dangling=true" -q)
        if [ -n "$dangling_images" ]; then
          docker rmi $dangling_images || echo "Failed to remove dangling images."
        else
          echo "No dangling images to remove."
        fi
        docker volume rm ${{ env.REDIS_VOLUME_NAME }} || echo "Volume deletion failed: ${{ env.REDIS_VOLUME_NAME }} does not exist."
